name: Dependencies
on:
  schedule:
    - cron:  '0 17 1 1-12 *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.7
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: "renovate-tomaz-z[bot]"
          RENOVATE_GIT_AUTHOR: "renovate-tomaz-z <159143984+renovate-tomaz-z[bot]@users.noreply.github.com>"
        with:
          token: ${{ steps.app-token.outputs.token }}
          renovate-version: 37.172.2